# Generated by Django 3.0.5 on 2021-06-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210614_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
