# Generated by Django 3.0.5 on 2021-06-22 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(help_text='Введите значение от 1 до 10', validators=[django.core.validators.MaxValueValidator(10, message='Максимальное значение - 10'), django.core.validators.MinValueValidator(1, message='Минимальное значение - 1')]),
        ),
    ]
