# Generated by Django 3.0.5 on 2021-06-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210618_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.CharField(default='Описание отсутсвует', max_length=600, null=True, verbose_name='Описание'),
        ),
    ]
