# Generated by Django 3.0.5 on 2021-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Рейтинг'),
        ),
    ]
