# Generated by Django 3.0.5 on 2021-06-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
