# Generated by Django 3.0.5 on 2021-06-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created',
            new_name='pub_date',
        ),
    ]
